### ISSUE TITLE
Tooltips inladen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#12]
De text voor de tooltips wordt nu meegegeven in de api (X)
Deze moet nog gevuld worden in de frontend:

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/7a9b7661-fd97-4ba2-9a79-7fa0f6188658)

**Comment by DonZandbergen** [comment]
Tooltips zijn niet zichtbaar



![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/4f61836a-749a-404c-aea7-c68a6ddd773d)

**Comment by WvanDam** [comment]
@DonZandbergen Dat komt omdat in alle mapsets de `note` waarde `null` is. In de publieke kaart van Schiedam zit overigens wel een ingevulde `note`.
