### ISSUE TITLE
Opmerkingen velden

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#13]
De opmerking velden bij INQUIRY, RECOVERY en INCIDENT (2 velden text) kunnen groot worden.

Bij meer dan 300 tekens in het text veld een knip invoegen naar een modal waarin de volledige tekst wordt weergegeven.

2 voorbeelden van de 3 velden:

![WhatsApp Image 2024-05-03 at 23 18 06_349904df](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/8f0845bb-a372-49b6-8383-580b1e2ca242)

![WhatsApp Image 2024-05-03 at 23 21 22_07c97859](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/f62f1ec6-8d52-48c0-90e9-bf956ec4f79d)

**Comment by yorickdewid** [comment]
Wellicht moet dit alleen te zien zijn in het modal, niet in de sidebar

**Comment by DonZandbergen** [comment]
Inderdaad beter alleen in modal

**Comment by WvanDam** [comment]
Dan krijg je wel mening van report & sample data in de modal, maar dat lijkt me inderdaad een betere plaats. Moet het dan nog ingekort worden?

**Comment by yorickdewid** [comment]
Nope, volledige text in de modal

**Comment by WvanDam** [comment]
ah... maar het gaat om incidenten... waar nu geen sprake is van een modal.

**Comment by WvanDam** [comment]
De inquiry en recovery notes zijn verplaatst naar de modal. In beide gevallen heb ik de note onderaan gezet. Bij inquiry is dit natuurlijk ff scrollen... en daar heeft de sample zelf bovenaan een note staan, dus daar is risico dat plaatsing bovenaan verwarrend kan zijn. Bij inquiry worden de properties in model ook ondergebracht in groepen. Ik heb nu even iets als placeholder gezet, maar verwacht niet dat de definitieve versie zal zijn.

**Comment by DonZandbergen** [comment]
De plaatsing in modal is niet juist. 
Originele idee was een nieuwe modal.
Nu staat het inderdaad gemengd, zoals @WvanDam  al voor waarschuwde.

Conform afstemming in overleg 7-5 wordt de tekst met ca. X aantal teken weer gegeven en in een tooltip verder getoond.

**Comment by WvanDam** [comment]
Tooltip wordt een gespiegelde versie van de tooltip in de linker sidebar naast mapset title (i)
