### ISSUE TITLE
De laag "bouwkundige eenheden" in mapset "Gebouw".

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#15]
De laag "bouwkundige eenheden" in mapset "Gebouw" wordt niet weergegeven.
Naam laag: "cluster"

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/a49b634b-56fc-4a2d-8f47-c6c97bba73e5)

**Comment by WvanDam** [comment]
Dit is een ticket voor Yorick. De UI bouwt de linker sidebar geheel op op basis van informatie uit de API. Dit betreft de beschikbare mapsets, incl. naam, legenda labels, legenda kleuren, en de daaraan gekoppelde Mapbox style en kaartlagen.
