### ISSUE TITLE
Lagen actief wanneer inactief

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#17]
Het komt voor dat lagen actief zijn maar de legenda niet is opengeklapt.

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/9e3fd2e9-66b7-43d7-8872-8e2d60caa7d6)

**Comment by yorickdewid** [comment]
Dit gebeurd oa als je voor het eerst inlogd
