### ISSUE TITLE
Scroll bar profiel

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#19]
Scrollbar in profiel is niet noodzakelijk en niet 'mooi' 
![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/ab6e5864-b5e0-4cf8-b4a0-8efaa44a8897)

**Comment by WvanDam** [comment]
Het is eenvoudig weg te halen. Bij een klein scherm (e.g. 13inch MacBook met reguliere resolutie) past de popup niet geheel op het scherm en zal (afhankelijk van de toegepaste CSS) een deel (incl. de knop) niet te zien zijn. Op tablets ontstaan wellicht vergelijkbare problemen.

**Comment by DonZandbergen** [comment]
Scrollbar uitzetten, bekijken we  het resultaat

**Comment by WvanDam** [comment]
Hierbij een reeks screenshots van de mogelijke css waarden. Standaard is de waarde 'auto'

**overflow: visible** 
Velden lopen door. Je kan niet naar beneden scrollen. 
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/49637885/bfc59ac5-7bc5-4409-bd4b-ecc8cdac4f74)

**overflow: hidden**
Velden worden afgebroken. Je kan niet naar beneden scrollen.
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/49637885/18358aa0-6b0d-4b8b-b63d-21b027a15259)

**overflow: scroll**
Altijd (ruimte voor) een scrollbar (kan ook alleen rechts of onder).
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/49637885/8a17f1af-c2b4-48e4-95e9-8cabed841690)

**overflow: auto**
Altijd (ruimte voor) een scrollbar aan de rechter zijde.
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/49637885/13b2c2fa-2506-4ab6-bc97-fa45ae14718c)

**Comment by WvanDam** [comment]
@DonZandbergen Het scherm is hier kleiner dan normaal, maar het geeft een idee. Ik heb zojuist in git de waarde naar 'hidden' aangepast.

**Comment by yorickdewid** [comment]
Lijkt me goed voor nu
