### ISSUE TITLE
Knoppen rechter sidebar altijd beschikbaar

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsWebFront#22]
![image](https://github.com/Laixer/FunderMapsWebFront/assets/7712841/312fa978-e08a-4c70-9443-bcd05cafdb8c)

Pand, Locatie, Fundering zijn altijd beschikbaar. In dat geval niet de knoppen disabled en enablen. Er is nu een korte periode tussen aanklikken en laden van de API data dat de buttons disabled zijn. Aangezien deze data altijd beschikbaar is, wellicht de knoppen altijd beschikbaar houden?

**Comment by DonZandbergen** [comment]
Statistiek en funderingsrisico zijn er ook altijd.
Alle tabs zijn altijd beschikbaar inderdaad.

**Comment by WvanDam** [comment]
Done. Op de tabbladen zelf moet sowieso ook nog iets gedaan worden mbt het inladen van nieuwe data.

De statistiek en funderingsrisico tabbladen moeten nog wel voorzien worden van data en opmaak.
