### ISSUE TITLE
Rechter sidebar overzichtspagina als er geen data is

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsWebFront#23]
Op een pand met een report klikken, report openen en dan een ander pand aanklikken levert een lege pane op:
![image](https://github.com/Laixer/FunderMapsWebFront/assets/7712841/b9ba8d5a-bfd7-4c56-b932-2e1d402efc79)

In dit geval terug springen naar overzichtspagina. Dit komt voor bij incident, recovery, inquiry

**Comment by WvanDam** [comment]
ah ja, dit is een bekend onderdeel van wat ik vrijdag bedoelde met "het is nog niet af" ;-)

**Comment by yorickdewid** [comment]
Prima, de issue staat er alvast :)

**Comment by WvanDam** [comment]
De tab wordt nu automatisch gesloten indien er geen informatie is. Geheel perfect is het nog niet, maar het is een begin.
