### ISSUE TITLE
DataField variant voor downloads toevoegen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#25]
Knop met link naar download van inquiry/recovery/incident ontbreekt.

**Comment by DonZandbergen** [comment]
Inquiry heeft 1 document
recovery heeft 1 document
incident heeft meerdere documetnen

**Comment by WvanDam** [comment]
Opgemerkt door Yorick: Recovery downloads gaat momenteel sws niet werken ivm onjuiste data in DB

**Comment by WvanDam** [comment]
@yorickdewid ik zie dat Don het ook heeft over incident downloads - en ik zie ook een documentFile property in IncidentReport, maar ik zie in de API geen endpoint

**Comment by yorickdewid** [comment]
Zoals besproken, dat kunnen meerdere filters zijn, en meestal images. Dat moet in een soort viewer komen. Niet voor nu

**Comment by WvanDam** [comment]
ah check dat is waar ook

**Comment by WvanDam** [comment]
@DonZandbergen  Ik heb de download functie toegevoegd aan Inquiry (onderaan de sidebar).

**Comment by DonZandbergen** [comment]
File won't download.

**Comment by WvanDam** [comment]
Klopt. Deze functie was uitgeschakeld ivm een build error in prod context.

**Comment by WvanDam** [comment]
@DonZandbergen Downloads zijn weer ingeschakeld
