### ISSUE TITLE
Controle/status geeft consistent "Geen data", hiervoor is data beschikbaar bij inquirry

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#26]

**Comment by WvanDam** [comment]
@yorickdewid Bedoel je 

<img width="300" alt="Screenshot 2024-05-06 at 17 02 00" src="https://github.com/Laixer/FunderMapsWebFront/assets/49637885/792a371e-8fcd-484e-8362-0262f323cb6e">

Dit ging idd mis, omdat de data bron een child-object is, maar is vrijdag gefixed.
