### ISSUE TITLE
Rotation map wordt niet opfeslagen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#27]

**Comment by WvanDam** [comment]
Relateerde overigens aan deze: 
https://github.com/Laixer/FunderMapsWebFront/issues/7

**Comment by yorickdewid** [comment]
rotation en pitch zijn andere dingen. Beide bijhouden in local session

**Comment by WvanDam** [comment]
In dat ticket werd ook aangegeven de rotation bij te houden in local storage, vandaar de link. En beiden done dus.

**Comment by yorickdewid** [comment]
Mooi!
