### ISSUE TITLE
zoom weergave

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#28]
Voorbeeld incidenten

**Comment by WvanDam** [comment]
Het gaat hier lijkt mij over de buurten, ed. welke op een ander zoom niveau zitten dan de gebouwen. 

Yorick vertelde dat er iets in de mapset `options` property meegenomen zou worden, maar deze waarde is vooralsnog `null`. De property is ook op het mapset object beschikbaar, terwijl er tussen de onderliggende lagen verschillen zijn in zoom niveaus. Ik weet ook nog hoe een ingevulde `options` er uit ziet.

**Comment by yorickdewid** [comment]
Options heeft nog geen invulling, maar kan nu een json object terug geven.

**Comment by WvanDam** [comment]
Dan pak ik dat op wanneer er invulling is. Want gewoon json parsen zonder er iets mee te doen heeft niet veel zin.
