### ISSUE TITLE
Remove "address" property from Incident object

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsWebFront#29]

**Comment by WvanDam** [comment]
In de UI laat ik het adres nu niet meer zien. Deploy onderweg

**Comment by yorickdewid** [comment]
De hele property gaat verdwijnen, en is_active is verwijderd vanmiddag

**Comment by WvanDam** [comment]
is_active van Address en ook Building? Ik heb beiden optioneel gemaakt in de UI code.

**Comment by yorickdewid** [comment]
In adres is hij helemaal weg, in building blijft ie

**Comment by WvanDam** [comment]
Done.
