### ISSUE TITLE
Wachtwoord herstel button

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#30]
Link achter button werkt niet

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/a738872b-52da-41a0-a5f0-cc51d44a7e03)

**Comment by WvanDam** [comment]
Fixed. Route name was opgegeven als 'Login' ipv 'login'. Deploy onderweg

**Comment by WvanDam** [comment]
@DonZandbergen Werkt de fix niet?

**Comment by DonZandbergen** [comment]
Issue was niet versleept naar in review.
Fix werkt.
