### ISSUE TITLE
Sample values are not displayed

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#37]
- [ ] De onderstaande velden worden niet getoond in de sample-modal. Er is wel smaple data van:

- Type fundering
- Funderingsherstel advies
- Grondwater niveau
- Grondwaterniveau bij ontwatering
(rood gekenmerkt in de afbeelding)

- [ ] De oranje velden moeten omgedraaid worden.
(staat meen ik wel goed in de excel)

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/dab4cae3-dbfa-42c3-bbd2-44702f56be01)

- [ ] Data type wijziging. Deze velden gaan nu uit van een integer. Het veld is echter een enum
- Resterende draagkracht paal 
- Kwaliteit draagkracht paal 
- Horizontale draagkracht paal 
(Dit stond fout in de excel, is aangepast in #2 )

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/ed277b05-a74f-4646-80ac-e726cf839499)
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/3232ba67-9d4d-44c8-bf1e-0820997faf2f)

=====================

Uitgewerkt voorbeeld:

Wanneer een pand aangeklikt met vastgesteld funderingstype = > onderzoeksgegeven => in de sample weergaven is het "fudneringstype" altijd "geen waarde" . Dat kan in dit geval niet, anders staat het funderingstype niet op kaart.

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/f97e16b8-0390-437a-8ff4-2fd064ed2583)

**Comment by WvanDam** [comment]
@DonZandbergen Kun je bij alle issues voortaan een pand id invoegen? Ik ben nu steeds onnodig tijd kwijt aan het opzoeken van het betreffende pand.

**Comment by DonZandbergen** [comment]
> @DonZandbergen Kun je bij alle issues voortaan een pand id invoegen? Ik ben nu steeds onnodig tijd kwijt aan het opzoeken van het betreffende pand.

Prima. De issue is echter pandid  onafhankelijk. Bij alle panden met onderzoek data beschikbaar.

**Comment by WvanDam** [comment]
@DonZandbergen Mijn ervaring is juist dat ik regelmatig (niet alleen mbt dit ticket) maar moeilijk panden kan vinden waar de API echt data terug geeft. 

Bijvoorbeeld: Praktisch alle values van de inquiry sample van NL.IMBAG.PAND.0034100000060767 zijn NULL. (zie onder)

Als er data in de database en Mapbox staat wil dat niet altijd zeggen dat het front-end óók data uit de API krijgt. Daarom dus graag wel echt altijd het pand id meegeven. 


````
{
            "id": 789320,
            "inquiry": 136265,
            "address": "gfm-3f1f31e105cc48e68ed609eccf3d14e7",
            "building": "NL.IMBAG.PAND.0034100000060767",
            "note": null,
            "builtYear": null,
            "substructure": null,
            "cpt": null,
            "monitoringWell": null,
            "groundwaterLevelTemp": null,
            "groundLevel": null,
            "groundwaterLevelNet": null,
            "foundationType": 3,
            "enforcementTerm": null,
            "recoveryAdvised": null,
            "damageCause": null,
            "damageCharacteristics": null,
            "constructionPile": null,
            "woodType": null,
            "woodEncroachement": null,
            "constructionLevel": null,
            "woodLevel": null,
            "pileDiameterTop": null,
            "pileDiameterBottom": null,
            "pileHeadLevel": null,
            "pileTipLevel": null,
            "foundationDepth": null,
            "masonLevel": null,
            "concreteChargerLength": null,
            "pileDistanceLength": null,
            "woodPenetrationDepth": null,
            "overallQuality": null,
            "woodQuality": null,
            "constructionQuality": null,
            "woodCapacityHorizontalQuality": null,
            "pileWoodCapacityVerticalQuality": null,
            "carryingCapacityQuality": null,
            "masonQuality": null,
            "woodQualityNecessity": null,
            "crackIndoorRestored": null,
            "crackIndoorType": null,
            "crackIndoorSize": null,
            "crackFacadeFrontRestored": null,
            "crackFacadeFrontType": null,
            "crackFacadeFrontSize": null,
            "crackFacadeBackRestored": null,
            "crackFacadeBackType": null,
            "crackFacadeBackSize": null,
            "crackFacadeLeftRestored": null,
            "crackFacadeLeftType": null,
            "crackFacadeLeftSize": null,
            "crackFacadeRightRestored": null,
            "crackFacadeRightType": null,
            "crackFacadeRightSize": null,
            "deformedFacade": null,
            "thresholdUpdownSkewed": null,
            "thresholdFrontLevel": null,
            "thresholdBackLevel": null,
            "skewedParallel": null,
            "skewedParallelFacade": null,
            "skewedPerpendicular": null,
            "skewedPerpendicularFacade": null,
            "settlementSpeed": null,
            "skewedWindowFrame": null,
            "facadeScanRisk": null,
            "createDate": "2022-12-22T12:01:24.882192Z",
            "updateDate": "2023-06-27T08:30:03.124297Z",
            "deleteDate": null
        }
````

**Comment by DonZandbergen** [comment]
Ah, check. Snap ik nu.
Ik ga een lijstje maken voor je .

**Comment by WvanDam** [comment]
@DonZandbergen 
Bij `foundationType` en `recoveryAdvised` wordt in de excel het inquiry report als databron opgegeven. In het report zitten deze properties echter niet verwerkt. Vandaar dat er geen data gevonden wordt. 

Gezien het grote aantal velden heb ik op diverse punten gewoon de Excel exact uitgevoerd zonder alles te controleren.

**Comment by WvanDam** [comment]
@yorickdewid @DonZandbergen Enums heb ik in eerst instantie gebaseerd op de API code. Daarna heb ik de labels uit de Excel gekoppeld aan de Enum values. In het geval van `monitoringWell` is er in de API geen sprake van een Enum, maar gewoon een string value. Ik zal hier net als bij eerdere gevallen waar de Enum (vooralsnog) ontbrak in de API een enum van maken op basis van de Excel.

**Comment by WvanDam** [comment]
@yorickdewid @DonZandbergen De verwisseling van de Enums `damageCause` en `damageCharacteristics` lijkt ook gaande te zijn in de API code:

https://github.com/Laixer/FunderMaps/blob/develop/src/FunderMaps.Core/Types/FoundationDamageCause.cs
https://github.com/Laixer/FunderMaps/blob/develop/src/FunderMaps.Core/Types/FoundationDamageCharacteristics.cs

Hoe verder?

**Comment by WvanDam** [comment]
@DonZandbergen 
`woodCapacityHorizontalQuality` heeft in de Excel 5 labels, maar in de API heeft de Enum (Quality) maar 4 mogelijke values. Idem voor `carryingCapacityQuality`. 

De field formatters voor de 3 enums zijn uitgeschakeld.

**Comment by DonZandbergen** [comment]
> Ah, check. Snap ik nu. Ik ga een lijstje maken voor je .

NL.IMBAG.PAND.0606100000020336

**Comment by DonZandbergen** [comment]
> `recoveryAdvised`

Deze waarden komen uit Inquiry Sample:
api/inquiry/{id}/sample

**Comment by DonZandbergen** [comment]
> [@DonZandbergen](https://github.com/DonZandbergen) `woodCapacityHorizontalQuality` heeft in de Excel 5 labels, maar in de API heeft de Enum (Quality) maar 4 mogelijke values. Idem voor `carryingCapacityQuality`.
> 
> De field formatters voor de 3 enums zijn uitgeschakeld.



> [@DonZandbergen](https://github.com/DonZandbergen) `woodCapacityHorizontalQuality` heeft in de Excel 5 labels, maar in de API heeft de Enum (Quality) maar 4 mogelijke values. Idem voor `carryingCapacityQuality`.
> 
> De field formatters voor de 3 enums zijn uitgeschakeld.

Klopt. Heb ik aangepast in excel:

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/06570d7c-4619-477c-a50d-2e6a0b83e21c)

**Comment by WvanDam** [comment]
> > [@yorickdewid](https://github.com/yorickdewid) [@DonZandbergen](https://github.com/DonZandbergen) Enums heb ik in eerst instantie gebaseerd op de API code. Daarna heb ik de labels uit de Excel gekoppeld aan de Enum values. In het geval van `monitoringWell` is er in de API geen sprake van een Enum, maar gewoon een string value. Ik zal hier net als bij eerdere gevallen waar de Enum (vooralsnog) ontbrak in de API een enum van maken op basis van de Excel.
> > edit: In de Excel is het ook geen enum. Idem voor `cpt`...
> 
> Deze snap ik niet. MonitoringWell en CPT zijn idnerdaad strings, zowel in maps-ap als in de excel.
> 
> De vraag over enums ging over:
> 
> * Resterende draagkracht paal
> * Kwaliteit draagkracht paal
> * Horizontale draagkracht paal

Ik zat mbt de enum opmerking eerst bij het screenshot er boven te kijken. Daar staat een 1 en een 3 achter monitoringWell en cpt, wat in mijn beleving niet veelzeggend is in relatie tot de labels.

**Comment by WvanDam** [comment]
> > `recoveryAdvised`
> 
> Deze waarden komen uit Inquiry Sample: api/inquiry/{id}/sample

Inderdaad. Daar kom ik hem nu ook tegen. Raar. Misschien was ik zojuist even te snel met zoeken oid. Ik heb iig meteen even de data source koppeling aangepast voor dat veld.

**Comment by DonZandbergen** [comment]
> [@yorickdewid](https://github.com/yorickdewid) [@DonZandbergen](https://github.com/DonZandbergen) De verwisseling van de Enums `damageCause` en `damageCharacteristics` lijkt ook gaande te zijn in de API code:
> 
> https://github.com/Laixer/FunderMaps/blob/develop/src/FunderMaps.Core/Types/FoundationDamageCause.cs https://github.com/Laixer/FunderMaps/blob/develop/src/FunderMaps.Core/Types/FoundationDamageCharacteristics.cs
> 
> Hoe verder?

Dit is juist:


**damageCharacteristics**
vertaling: Geconstateerde schade 
src/FunderMaps.Core/Types/FoundationDamageCharacteristics.cs


0 jamming_door_window
1 crack
2 skewed
3 crawlspace_flooding
4 threshold_above_subsurface
5 threshold_below_subsurface
6 crooked_floor_wall

0 Klemmende deuren en ramen
1 Scheuren
2 Scheefstand
3 Water in kruipruimte
4 Drempel boven maaiveld
5 Drempel onder maaiveld
6 Scheve vloer of wand


**damageCause**
Oorzaak funderingsschade 
src/FunderMaps.Core/Types/FoundationDamageCause.cs
0 Drainage
1 ConstructionFlaw
2 Drystand
3 Overcharge
4 OverchargeNegativeCling
5 NegativeCling
6 BioInfection
8 FungusInfection
9 BioFungusInfection
10 FoundationFlaw
11 ConstructionHeave
12 Subsidence
13 Vegetation
14 Gas
15 Vibrations
16 PartialFoundationRecovery
17 JapanseKnotweed
18 GroundwaterLevelReduction

0 Te lage grondwaterstand
1 Constructiefouten
2 Droogstand houten paalkop
3 Overbelasting
4 Overbelastingen / of negatievekleef
5 Negatievekleef
6 Bacterieleaantasting (palenpest)
8 Schimmelaantasting (paalrot)
9 Bacterieleen / of schimmelaantasting
10 Funderingsfouten
11 Opdrukking pand
12 Verzakking
13 Beschadiging fundering door planten en wortels
14 Gaswinning
15 Trillingen
16 Partieel funderingsherstel
17 Beschadiging fundering door japanse duizendknoop
18 Verlaging van grondwaterstand

(Excel is aangepast)

**Comment by WvanDam** [comment]
@DonZandbergen groundwaterLevelNet en groundwaterLevelTemp waren in de code ingevoerd groundWaterLevelNet en groundWaterLevelTemp, omdat ik Net en Temp aan groundWaterLevel had toegevoegd. In die laatste is het `groundWater`. In de andere 2 had het dus `groundwater` moeten zijn.

**Comment by WvanDam** [comment]
`foundationType` en `recoveryAdvised` haal ik nu uit de sample data.
