### ISSUE TITLE
Icons Risk

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#39]
Kan je hier je conform het design de gekleurde incons A-E plaatsen?
Het tekst label ook graag behouden.

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/e4e9db20-2a0d-4d09-ae8f-d563931dff9a)

**Comment by WvanDam** [comment]
Toegepast op 'drystandRisk', 'dewateringDepthRisk', 'bioInfectionRisk' en 'unclassifiedRisk', op basis van EFoundationRisk classificatie (A t/m E). 

Daarnaast heb ik 'negativeclingRisk', 'negativeclingReliability', 'differentialsettlementRisk', 'differentialsettlementReliability' en 'facadescanRisk' verborgen, omdat deze als out of scope zijn aangemerkt in de excel.
