### ISSUE TITLE
Fallback to API if PDOK has no results

### ISSUE THREAD

**Issue by WvanDam** [Laixer/FunderMapsWebFront#41]
Detect whether the query contains a BAG id. If so, go to API first.

**Comment by yorickdewid** [comment]
Ik zou zeggen andersom. Eerst PDOK daarna onze eigen API

**Comment by WvanDam** [comment]
Zoeken op 0642100000002052 of een string met 'bag' of 'BAG' controleert nu eerst bij de Fundermapds API of het een bekend pand id is. Indien dit het geval is, wordt er naar het pand genavigeerd.
