### ISSUE TITLE
Link bij herstelinformatie

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#42]
De tekst-link en het abel "onbekende eigenschap" mag eruit.

![Image](https://github.com/Laixer/FunderMaps/assets/46600362/d47e4caa-67f2-4350-87f8-a446ad5be29b)

Dit wordt de PDF knip voor download files #25 

Voorbeeld NL.IMBAG.PAND.0599100000676401

**Comment by WvanDam** [comment]
Staat daar ivm WIP mbt https://github.com/Laixer/FunderMapsWebFront/issues/25
