### ISSUE TITLE
Labels: "Funderingstype" en "funderingsherstel advies"

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#43]
Labels: "Funderingstype" en "funderingsherstel advies" in sample modal geven nu " onbekende eigenschap".

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/079ffd3e-f630-463b-9006-731f9f9a1c75)

Voorbeelden:
NL.IMBAG.PAND.0599100000656959
NL.IMBAG.PAND.0599100000202265

**Comment by WvanDam** [comment]
Done. De labels hingen nog aan het inquiry report ipv inquiry sample.
