### ISSUE TITLE
Update info tablad "Locatie" en "Pand" bij aanklikken panden

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#45]
De informatie in het tabblad "locatie" update zich niet bij het opnieuw aanklikken van een pand.

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/3bb62904-0d02-4c6a-aa78-021af86a7fb1)

Ook het BAG Pand ID in tabblad "Pand" update zich niet ij het aanklikken van een ander pand:
![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/d5d63ef8-4980-4417-a460-bd1c5f3779ca)

**Comment by WvanDam** [comment]
Kun je in de console kijken of er een foutmelding te zien is?

**Comment by WvanDam** [comment]
Ok. Ik weet niet zo goed waar die error vandaan zou komen. Mogelijk is het iets met local/session storage. JSON.parse wordt gebruikt om de center coordinaten van text naar bruikbare data om te zetten. Daar heb ik nu een try ... catch omheen gezet, met een specifieke console melding indien dat inderdaad mis gaat. Dit heb ik op alle plaatsen waar JSON.parse wordt gebruikt toegepast. 

De functie namen in de foutmelding leveren verder geen resultaat op (ook niet in google) en content.js is geen onderdeel van de applicatie code. Misschien is het een Chrome plugin? 

Los daarvan: ik kan het helaas vooralsnog niet reproduceren. Is dit een continu probleem? Of soms ? Gaat het om specifieke gebouwen? 

Wanneer ik vanaf Oosteinde 4 in Zevenaar naar een ander pand ga, of vanaf een ander pand naar dit adres ga, dan werkt het prima. Dit is bij het weergeven van de "Eigenaar" layer in de Pand mapset, om ook die context gelijk te hebben.

**Comment by WvanDam** [comment]
Aha. Het is het pand id op het "pand" tabblad dat niet wijzigt. In de url en in het kader boven de menu items veranderd het pand id wel mee.
