### ISSUE TITLE
Eerste keer laden pagina funderingstype  kaartlaag tonen

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#5]
Bij het laden van de pagina de kaartlaag "funderingstype" + "funderingstype afgeleid" direct tonen.
De legenda uitgeklapt op die twee lagen weergeven.

**Comment by yorickdewid** [comment]
En zoom naar het eerste niveau waarom de features in beeld komen

**Comment by WvanDam** [comment]
Default zoom is nu 15. Dit is volgens Mapbox de zoom waarop gebouwen zichtbaar worden.

**Comment by WvanDam** [comment]
In het kader van dit ticket voeg ik 2 env vars toe:

VITE_DEFAULT_MAPSET_ID = c81d4c1b-cc11-4f80-b324-9ab7e6cefd99
VITE_DEFAULT_LAYERS = foundation-type-cluster,foundation-type-established

Ik neem bovenstaande waarden ook op als hardcoded defaults indien de env's leeg zijn.

**Comment by yorickdewid** [comment]
Toegevoegd

**Comment by WvanDam** [comment]
Deze functie is onderweg naar de demo omgeving

**Comment by WvanDam** [comment]
ah. De linker sidebar is niet default uitgeklapt. Dit heeft nog wat extra werk nodig. 

Wellicht ga ik in de session storage ook bijhouden of de sidebar open is of niet. Als er dan geen waarde beschikbaar is, gooi ik de sidebar open. Anders wordt het vermoedelijk een bak meer code om niet op ongewenste momenten de sidebar open te gooien.

**Comment by yorickdewid** [comment]
Lijkt me prima
