### ISSUE TITLE
Bug bij schakelen openbare en ingelogd kaarten

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#54]
**Openbare kaarten**
1) Bij het benaderen van de openbare open de openbare kaart niet in de betreffende gemeente. Enkele voorbeelden van openbare kaarten:
  - Woerden: https://maps.fundermaps.com/kaart/woerden-publiek
  - Oudewater: https://maps.fundermaps.com/kaart/oudewater-publiek
  - Dordrecht: https://maps.fundermaps.com/kaart/dordrecht-publiek
2) Vanuit openbare kaart inloggen (Fm account)) en daarna uitloggen blijf je hangen binnen de openbare kaart. Als je dan weer probeert in te loggen op maps.fundermaps.com blijf je binnen de eerdere bezochte openbare kaart hangen.
- Vanuit de legenda de kaartlagen aan en uitzetten schakelen de lagen in de kaart niet. 

**Ingelogde kaarten / accounts**
3) Het komt regelmatig voor dat je niet kan inloggen (geen kaarten beschikbaar.) Via de inlogfucntie op de openbare kaart lukt dan dan weer wel.

**Comment by WvanDam** [comment]
1. Dat de kaart bij een openbare kaart niet in de betreffende gemeente start komt omdat het meegeven van kaart opties (e.g. initiële coordinaten en zoom) in de mapset nog niet is uitgewerkt, en daarom dus ook nog niet is gebouwd. Als nieuwe bezoeker start je daarom ergens midden in het land (de default coordinaten). Hierbij meteen ook de vraag wat te doen bij het wisselen tussen mapsets tijdens een actieve sessie, waarbij de gebruiker al naar een punt op de kaart kijkt. Tevens wat te doen bij coordinaten vanuit de url / pand / session storage. Wat is de prioriteitenlijst?  pand => url => huidig => session => mapset? Of pand => url => huidig => mapset => session ?

2. Ik denk dat ik weet wat er aan de hand is. Voorheen kreeg je bij het ophalen van een publieke mapset ook de prive mapsets mee indien je was ingelogd. Dit is niet langer het geval, en hier moet in het front-end vermoedelijk nog een aanpassing op worden gemaakt.

2b Het vanuit de legenda de kaartlagen aan en uitzetten. Heb je een voorbeeld? En begrijp ik dat dit enkele publieke kaarten betreft? 

3. Dit is raar. Heb je meer info?

**Comment by DonZandbergen** [comment]
Punt 1:
Je krijgt "options" terug in de API. Daarin zit een Lon-Lat voor centerpoint per account. Deze is op het moment alleen gevuld voor account schiedam@fundermaps.com.

**Comment by DonZandbergen** [comment]
> Hoe ziet dat er precies uit? Of beter: valt dit ook op [wouter@fundermaps.com](mailto:wouter@fundermaps.com) toe te passen, zodat ik er mee kan testen?

@yorickdewid  Op Organisatie FunderMaps: lat=51.91749693646554&lng=4.476634809875492
