### ISSUE TITLE
Restore Search Functionality for Cities and Places in maps.fundermaps.com

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#56]
## Description
In maps.fundermaps.com, the ability to search for cities and places is a significant missing feature. This functionality was previously available and needs to be restored.

## Actions

- [ ] Review the previous implementation of the search functionality for cities and places.
- [ ] Update the search API to include cities and places.
- [ ] Modify the frontend to support searching for cities and places.
- [ ] Test the search functionality to ensure it works correctly for cities and places.
- [ ] Deploy the updated search feature to maps.fundermaps.com.

## Expected Behavior
Users should be able to search for cities and places in maps.fundermaps.com as they could previously. The search results should accurately reflect the cities and places available in the database.

## Screenshots
![Image](https://github.com/user-attachments/assets/b5669dc3-53b5-4666-b19b-9f074cd8bd35)

**Comment by yorickdewid** [comment]
Allow for searching on "woonplaats" "postcode" and "adres" in that order.
