### ISSUE TITLE
Dubbele rapportweergave bij onderzoeksgegevens

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#58]
Bij het bekijken van onderzoeksgegevens voor een adres dat rapporten heeft worden aanvankelijk meerdere dubbele rapporten weergegeven. Dit is echter incorrect, aangezien enkele van deze rapporten dezelfde zijn en naar hetzelfde document linken.

Beschrijving voorbeeld:

1. Zoek op in het zoekveld op "Oostergoostraat 80, 9001CN Grou".
2. Ga naar "Bekijk onderzoeksgegevens".
3. Volgens de paginering zijn er 4 rapporten beschikbaar.
4. Dit zijn 2 keer dezelfde, namelijk inquiryID 140681 en 139340.
5. Beide bestanden linken naar hetzelfde document.
6. Ververs nu de pagina.
7. Nu zijn er volgens de paginering nog maar 2 rapporten (wat correct is).
8. En wordt er gelinkt naar 2 dezelfde documenten (die correct zijn).

**Comment by WvanDam** [comment]
@DonZandbergen Deze is opgelost. 

Het probleem was dat de samples 2 keer werden ingeladen. Bij een klik op de kaart was dit met "NL.IMBAG.PAND.0055100000264026" als buildingId. Via de zoekfunctie was het met "0055200000281567" als buildingId. 

Dat bij een id alias de data voor de tweede (of meer) keer wordt ingeladen valt niet te wijzigen, omdat de API het gegeven id moet vertalen naar het pand en het front-end zich hier niet mee moet bemoeien. Het is op zich ook geen probleem, zolang de data gescheiden wordt op basis van het pand id. En dit is dus hoe de pand data wordt opgeslagen. 

Het ging mis bij de samples omdat deze op basis van het reportId ingeladen worden, en nieuwe samples toegevoegd worden aan de array, ipv dat de array vervangen wordt. Er zit nu een check op om duplicaten te voorkomen. Idem bij recovery samples.
