### ISSUE TITLE
Wachtwoord wijzigen opnemen in menu

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#6]
Wachtwoord wijzigen opnemen onder profiel in applicatie

![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/ef59f679-9260-46ae-a3f1-f0fff1a0272d)

**Comment by yorickdewid** [comment]
Ik kan hier niks aan doen, waarom ben ik toegekend?
