### ISSUE TITLE
Set Default Map Center to Organization's or Municipality's Area

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#61]
### Current Situation
When opening the map, it defaults to Amersfoort. Although local storage retains some information, it is often cleared on corporate networks, causing the map to reset to Amersfoort instead of the organization's or municipality's center.

### Problem
This results in inconvenience and extra steps for users who must repeatedly navigate to their desired location. For organizations operating in specific municipalities, it is more efficient if the map opens directly to their work area.

### Desired Situation
When a user opens the map, it should automatically center on the visible area of the relevant organization or municipality, rather than defaulting to Amersfoort.

## Actions

- [ ] Identify the organization's or municipality's center coordinates for each user.
- [ ] Update the initial map loading logic to check for the user's organization or municipality.
- [ ] Modify the map initialization code to center the map on the user's organization or municipality's area when local storage is empty or cleared.
- [ ] Test the changes to ensure the map centers correctly for different users.
- [ ] Deploy the changes to maps.fundermaps.com.

## Expected Behavior
The map should automatically center on the relevant organization or municipality's area when a user opens it for the first time or when local storage is cleared, instead of defaulting to Amersfoort.

Relates to: https://github.com/Laixer/FunderMaps/issues/875

**Comment by yorickdewid** [comment]
Volgens mij was dit al opgelost in een eerdere issue

**Comment by WvanDam** [comment]
Nieuwe center point is Amsterdam
