### ISSUE TITLE
Add Quality Layer to `REPORT` Mapset

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#63]
## Description
A new map layer needs to be added to the `REPORT` mapset. This layer is named "kwaliteit" and is found in the Mapbox style `analysis_report` as the layer `overall-quality`.

## Actions

- [ ] Add the `overall-quality` layer from the Mapbox style `analysis_report` to the `REPORT` mapset.
- [x] Update the legend for the `overall-quality` layer using the colors specified in the [Standard Map Colors](https://github.com/Laixer/FunderMaps/wiki/Standaard-kaart-kleuren).
- [ ] Ensure the new layer is correctly applied and displayed in the map application.
- [ ] Test the changes to confirm the layer is accurately added and the legend is correctly displayed.
- [ ] Deploy the updated mapset to maps.fundermaps.com.

## Expected Behavior
The `overall-quality` layer should be available in the `REPORT` mapset, and the legend should reflect the specified colors from the standard map colors.

## Additional Information
Refer to the [Standard Map Colors](https://github.com/Laixer/FunderMaps/wiki/Standaard-kaart-kleuren) for the legend color scheme to be used.

## Screenshots

![image](https://github.com/user-attachments/assets/a9ee2ffb-acae-44b9-a8b8-fb41ef60fc7c)

![image](https://github.com/user-attachments/assets/b383425d-d169-4801-a90c-c764eed74e06)

**Comment by yorickdewid** [comment]
Issue is unclear

**Comment by DonZandbergen** [comment]
Concreet: er is een attribuut overall-quality.
Deze is reeds in de tilset opgenomen en is reeds in de style “report” opgenomen als laag.

Deze laag moet in de maps.fundermaps onder  “rapportage” worden toegevoegd als met de naam “kwaliteit”

Met vriendelijke groet,

Don Zandbergen
Laixer
________________________________
Van: Yorick de Wid ***@***.***>
Verzonden: Monday, August 5, 2024 12:24:40 PM
Aan: Laixer/FunderMapsWebFront ***@***.***>
CC: Don Zandbergen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Laixer/FunderMapsWebFront] Add Quality Layer to `REPORT` Mapset (Issue #63)


Issue is unclear
