### ISSUE TITLE
Show "no info" when API returns 404

### ISSUE THREAD

**Issue by yorickdewid** [Laixer/FunderMapsWebFront#69]

**Comment by WvanDam** [comment]
context: when clicking on a building, sometimes 1 of 4 calls fails. Currently nothing is shown about this. It needs to show a warning (e.g. no info).

**Comment by yorickdewid** [comment]
@WvanDam this is done?

**Comment by WvanDam** [comment]
Not yet. I'm thinking on how best to process the error.
