### ISSUE TITLE
Bij (opnieuw) laden van pagina

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#7]
![image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/3056745f-9bb4-4b2d-a7db-9d369a043fb9)

**Comment by DonZandbergen** [comment]
Locatie, pitch en rotatie moet opgeslagen worden in local storage.

**Comment by WvanDam** [comment]
De hoek werd nog niet bijgehouden, maar nu wel. De rest werd reeds bijgehouden in sessionStorage, maar heb ik nu gewijzigd naar het meer permanente localStorage.
