### ISSUE TITLE
Pin op coordinaten van geselecteerde pand op kaart weergeven

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#8]
Highlight pand in kaart bij on-click & on select vanuit search

**Comment by WvanDam** [comment]
@DonZandbergen Kan dit aan de hand van een pin? Want anders wordt het mogelijk nog een karwei om dit goed af te stemmen en heb je ook iets van een legenda nodig om de kleur te duiden. Een pin is ook consistent met het klikken op een resultaat uit de zoek functie.

**Comment by DonZandbergen** [comment]
> @DonZandbergen Kan dit aan de hand van een pin? Want anders wordt het mogelijk nog een karwei om dit goed af te stemmen en heb je ook iets van een legenda nodig om de kleur te duiden. Een pin is ook consistent met het klikken op een resultaat uit de zoek functie.

Pin is prima, als maar duidelijk is dat bij rondklikken zichtbaar is om welk om welk pand op kaart het gaat.

**Comment by DonZandbergen** [comment]
> @DonZandbergen Kan dit aan de hand van een pin? Want anders wordt het mogelijk nog een karwei om dit goed af te stemmen en heb je ook iets van een legenda nodig om de kleur te duiden. Een pin is ook consistent met het klikken op een resultaat uit de zoek functie.

Pin is prima, als maar duidelijk is dat bij rondklikken zichtbaar is om welk pand het gaat.

**Comment by WvanDam** [comment]
De coordinaten van het pand komen inmiddels terug vanuit de API. Deze kunnen nu gebruikt worden voor de pin plaatsing ipv de coordinaten uit het click event.

**Comment by WvanDam** [comment]
Staat in git.
