### ISSUE TITLE
Routes incl coördinaten en BAGID in URL

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsWebFront#9]
Neem lat long coördinaten op in de URL, incl zoom niveau van de kaart zodat de URL goed te delen valt.
Een BAGID meenemen heeft ook de voorkeur zodat de rechter sidebar direct beschikbaar is en informatie geeft.

**Comment by WvanDam** [comment]
@DonZandbergen De routes aanvullen staat nog op de todo. Mijn plan was om het gebouw id en het actieve tabblad in de url te verwerken. 

`<baseUrl>/<orgId>/<mapsetId>/id/<pandId>/<tabblad>`

Idealiter komen van de `org` en `mapset` slugs beschikbaar ipv ids, zodat de urls wat gebruikersvriendelijker zijn. Het gaat in beide gevallen om een kleine dataset, dus dat moet kunnen denk ik. 

lat lng en zoom niveau had ik niet aan gedacht. Dat kan wellicht als query string, zodat dit toe te voegen is ongeacht wat je aan het bekijken bent.

**Comment by yorickdewid** [comment]
Ja query string, net als Google maps

**Comment by DonZandbergen** [comment]
In publieke kaart rechter sidebar zichtbaar met de niet-rode delen:

![Image](https://github.com/Laixer/FunderMapsWebFront/assets/46600362/156465bf-38e0-4bdd-bed7-be352728aec6)

Als je ingelogd bent wel alles zichtbaar.

**Comment by WvanDam** [comment]
Dinsdag is besproken dat van deze opbouw
`<baseUrl>/<orgId>/<mapsetId>/id/<pandId>/<tabblad>`

orgId kan komen te vervallen, omdat een orgs mapsets delen. Het gevolg is wel dat iemand met meerdere orgs niet kan bepalen in welke org hij binnen komt, waarbij tevens een probleem kan ontstaan indien niet alle orgs toegang hebben tot dezelfde set mapsets.

**Comment by yorickdewid** [comment]
Dat is terecht ja, maar dat is voor nu wel een heel klein probleem

**Comment by WvanDam** [comment]
ok. Als later toch orgId toegevoegd moet worden, wordt het werkend houden van alle tot dan gedeelde urls mogelijk lastig.

**Comment by yorickdewid** [comment]
Is dit nu in review?

**Comment by WvanDam** [comment]
Nog niet 100%. Zie ook https://github.com/orgs/Laixer/projects/8/views/2?filterQuery=repo%3A%22Laixer%2FFunderMapsWebFront%22&pane=issue&itemId=62694502

Daarnaast is het onderdeel met het bijhouden van de actieve sidebar tab in de url nog niet geregeld, evenals de query string (coordinaten). Dit laatste is ook leuk als het conflicteert met de coordinaten van het pand. 

Vraag daarbij: gaan de coordinaten in de url dan voor de coordinaten van het pand? Of andersom?

**Comment by yorickdewid** [comment]
1. PAND
2. LatLong

Pand geeft altijd meer info lijkt me zo

**Comment by WvanDam** [comment]
De rechter sidebar blijft nu open bij het schakelen tussen mapsets.

**Comment by WvanDam** [comment]
Je kan nu ook direct naar een specifiek tabblad in de rechter sidebar. Nu nog de query string coordinaten. Deze worden dus enkel benut indien het een `mapset` route betreft (kaart weergave zonder pand id).

**Comment by WvanDam** [comment]
De LatLng van het center punt van de kaart wordt nu bijgehouden in de query string van de url. 

Bij het openen van een gedeelde pagina is dit de prio mbt de init opties van Mapbox:
- query string
- local storage
- [5.2913, 52.1326] (hardcoded default)

Indien er vervolgens een pandId beschikbaar is, wordt de data opgehaald en start er een FlyTo beweging naar de coordinaten van het pand.
